### ISSUE TITLE
401 Unauthorized on v1.2.0, Works Fine on v1.1.0

### ISSUE THREAD

**Issue by MAbdElRaouf** [requests/requests-ntlm#136]
A script that utilizes requests-ntlm.HttpNtlmAuth to authenticate with a website had been working fine until I upgraded the package to the latest version 1.2.0 then it started throwing 401 unauthorized exception. Downgrading to v1.1.0 without any changes to the code resolved the issue.

```
import requests
from requests_ntlm import HttpNtlmAuth


response = requests.get(
    "http://url",
    auth=HttpNtlmAuth("username", "password"),
)

# v1.1.0: 200 OK
# v1.2.0: 401 Unauthorized
```

Note: the script runs behind an HTTP corporate proxy if it makes any difference.

**Comment by cebaa** [comment]
1.2.0 replaced ntlm_auth with spnego:

https://github.com/requests/requests-ntlm/compare/v1.1.0...v1.2.0#diff-3590900fb531e3b46542fdf34352cfdd58edf42d2fca824e5d518ab3375e6e4aL9

I suspect they are doing things differently under the hood.

**Comment by jborean93** [comment]
The pyspnego library should be support all the same features as the old dependency `ntlm-auth` (I wrote both of them). If the newer version is failing then trying to see what differences in the token will hopefully narrow down what might be happening to them. You can run `python -m spnego --token $BASE64_TOKEN`. NTLM exchanges 3 tokens across a request so comparing them all might help to identify the differences. 

An example of all three messages in an exchange are shown below (I used Wireshark to get these values). A not in that the nonces will have different values per exchange and `NTProofStr` is a hash of the password + nonce information used so they will differ across the exchanges. Some common examples I've seen in the past

* The `Version` field might be omitted in the messages and some servers might mandate it in some circumstances
* The `MSV_AV_TARGET_NAME` AvPair in the authentication message is set to a unknown host which may flag Windows (I'm not sure if there is a policy for this or not)

Ultimately this issue is not something I can replicate, more information will need to be provided to compare the differences between the old and new way to find out why this might be happening for you.

#### Negotiate Message

```bash
$ python -m spnego --format yaml --token TlRMTVNTUAABAAAAN4II4gAAAAAoAAAAAAAAACgAAAAACQEAAAAADw==
```

```yaml
MessageType: NEGOTIATE_MESSAGE (1)
Data:
  NegotiateFlags:
    raw: 3792208439
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_KEY_EXCH (1073741824)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_VERSION (33554432)
    - NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY (524288)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_OEM (2)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  DomainNameFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 40
  WorkstationFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 40
  Version:
    Major: 0
    Minor: 9
    Build: 1
    Reserved: '000000'
    NTLMRevision: 15
  Payload:
    DomainName:
    Workstation:
RawData: 4E544C4D5353500001000000378208E200000000280000000000000028000000000901000000000F
```

#### Challenge Message

```bash
$ python -m spnego --format yaml --token TlRMTVNTUAACAAAADAAMADgAAAA1goniQInKuHLN48QAAAAAAAAAAJwAnABEAAAACgB8TwAAAA9EAE8ATQBBAEkATgACAAwARABPAE0AQQBJAE4AAQAUAFMARQBSAFYARQBSADIAMAAyADIABAAWAGQAbwBtAGEAaQBuAC4AdABlAHMAdAADACwAUwBFAFIAVgBFAFIAMgAwADIAMgAuAGQAbwBtAGEAaQBuAC4AdABlAHMAdAAFABYAZABvAG0AYQBpAG4ALgB0AGUAcwB0AAcACACdH8ukxsTZAQAAAAA=
```

```yaml
MessageType: CHALLENGE_MESSAGE (2)
Data:
  TargetNameFields:
    Len: 12
    MaxLen: 12
    BufferOffset: 56
  NegotiateFlags:
    raw: 3800662581
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_KEY_EXCH (1073741824)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_VERSION (33554432)
    - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
    - NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY (524288)
    - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  ServerChallenge: 4089CAB872CDE3C4
  Reserved: '0000000000000000'
  TargetInfoFields:
    Len: 156
    MaxLen: 156
    BufferOffset: 68
  Version:
    Major: 10
    Minor: 0
    Build: 20348
    Reserved: '000000'
    NTLMRevision: 15
  Payload:
    TargetName: DOMAIN
    TargetInfo:
    - AvId: MSV_AV_NB_DOMAIN_NAME (2)
      Value: DOMAIN
    - AvId: MSV_AV_NB_COMPUTER_NAME (1)
      Value: SERVER2022
    - AvId: MSV_AV_DNS_DOMAIN_NAME (4)
      Value: domain.test
    - AvId: MSV_AV_DNS_COMPUTER_NAME (3)
      Value: SERVER2022.domain.test
    - AvId: MSV_AV_DNS_TREE_NAME (5)
      Value: domain.test
    - AvId: MSV_AV_TIMESTAMP (7)
      Value: '2023-08-01T22:22:23.1484317Z'
    - AvId: MSV_AV_EOL (0)
      Value:
RawData:
  4E544C4D53535000020000000C000C0038000000358289E24089CAB872CDE3C400000000000000009C009C00440000000A007C4F0000000F44004F004D00410049004E0002000C0044004F004D00410049004E000100140053004500520056004500520032003000320032000400160064006F006D00610069006E002E00740065007300740003002C0053004500520056004500520032003000320032002E0064006F006D00610069006E002E0074006500730074000500160064006F006D00610069006E002E007400650073007400070008009D1FCBA4C6C4D90100000000
```

#### Authenticate Message

```bash
$ python -m spnego --format yaml --token TlRMTVNTUAADAAAAGAAYAFgAAAD4APgAcAAAAAAAAABoAQAANAA0AGgBAAAaABoAnAEAABAAEAC2AQAANYKJ4gAJAQAAAAAPLYyl/bMH17nMmNwANMCtpwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMHtVmMbCoV1TZuSGbteLeoBAQAAAAAAAJ0fy6TGxNkBh5sLMRRmtb4AAAAAAgAMAEQATwBNAEEASQBOAAEAFABTAEUAUgBWAEUAUgAyADAAMgAyAAQAFgBkAG8AbQBhAGkAbgAuAHQAZQBzAHQAAwAsAFMARQBSAFYARQBSADIAMAAyADIALgBkAG8AbQBhAGkAbgAuAHQAZQBzAHQABQAWAGQAbwBtAGEAaQBuAC4AdABlAHMAdAAHAAgAnR/LpMbE2QEJACAAaABvAHMAdAAvAHUAbgBzAHAAZQBjAGkAZgBpAGUAZAAGAAQAAgAAAAAAAAAAAAAAdgBhAGcAcgBhAG4AdAAtAGQAbwBtAGEAaQBuAEAARABPAE0AQQBJAE4ALgBUAEUAUwBUAEoAQgBPAFIARQBBAE4ALQBMAEkATgBVAFgA5ucL7LuCRwB+Lnly16t1DA==
```

```yaml
MessageType: AUTHENTICATE_MESSAGE (3)
Data:
  LmChallengeResponseFields:
    Len: 24
    MaxLen: 24
    BufferOffset: 88
  NtChallengeResponseFields:
    Len: 248
    MaxLen: 248
    BufferOffset: 112
  DomainNameFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 360
  UserNameFields:
    Len: 52
    MaxLen: 52
    BufferOffset: 360
  WorkstationFields:
    Len: 26
    MaxLen: 26
    BufferOffset: 412
  EncryptedRandomSessionKeyFields:
    Len: 16
    MaxLen: 16
    BufferOffset: 438
  NegotiateFlags:
    raw: 3800662581
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_KEY_EXCH (1073741824)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_VERSION (33554432)
    - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
    - NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY (524288)
    - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  Version:
    Major: 0
    Minor: 9
    Build: 1
    Reserved: '000000'
    NTLMRevision: 15
  MIC: 2D8CA5FDB307D7B9CC98DC0034C0ADA7
  Payload:
    LmChallengeResponse:
      ResponseType: LMv2
      LMProofStr: '00000000000000000000000000000000'
      ChallengeFromClient: '0000000000000000'
    NtChallengeResponse:
      ResponseType: NTLMv2
      NTProofStr: C1ED56631B0A85754D9B9219BB5E2DEA
      ClientChallenge:
        RespType: 1
        HiRespType: 1
        Reserved1: 0
        Reserved2: 0
        TimeStamp: '2023-08-01T22:22:23.1484317Z'
        ChallengeFromClient: 879B0B311466B5BE
        Reserved3: 0
        AvPairs:
        - AvId: MSV_AV_NB_DOMAIN_NAME (2)
          Value: DOMAIN
        - AvId: MSV_AV_NB_COMPUTER_NAME (1)
          Value: SERVER2022
        - AvId: MSV_AV_DNS_DOMAIN_NAME (4)
          Value: domain.test
        - AvId: MSV_AV_DNS_COMPUTER_NAME (3)
          Value: SERVER2022.domain.test
        - AvId: MSV_AV_DNS_TREE_NAME (5)
          Value: domain.test
        - AvId: MSV_AV_TIMESTAMP (7)
          Value: '2023-08-01T22:22:23.1484317Z'
        - AvId: MSV_AV_TARGET_NAME (9)
          Value: host/unspecified
        - AvId: MSV_AV_FLAGS (6)
          Value:
            raw: 2
            flags:
            - MIC_PROVIDED (2)
        - AvId: MSV_AV_EOL (0)
          Value:
        Reserved4: 0
    DomainName:
    UserName: vagrant-domain@DOMAIN.TEST
    Workstation: JBOREAN-LINUX
    EncryptedRandomSessionKey: E6E70BECBB8247007E2E7972D7AB750C
  SessionKey: Failed to derive
RawData:
  4E544C4D53535000030000001800180058000000F800F80070000000000000006801000034003400680100001A001A009C01000010001000B6010000358289E2000901000000000F2D8CA5FDB307D7B9CC98DC0034C0ADA7000000000000000000000000000000000000000000000000C1ED56631B0A85754D9B9219BB5E2DEA01010000000000009D1FCBA4C6C4D901879B0B311466B5BE0000000002000C0044004F004D00410049004E000100140053004500520056004500520032003000320032000400160064006F006D00610069006E002E00740065007300740003002C0053004500520056004500520032003000320032002E0064006F006D00610069006E002E0074006500730074000500160064006F006D00610069006E002E007400650073007400070008009D1FCBA4C6C4D9010900200068006F00730074002F0075006E0073007000650063006900660069006500640006000400020000000000000000000000760061006700720061006E0074002D0064006F006D00610069006E00400044004F004D00410049004E002E0054004500530054004A0042004F005200450041004E002D004C0049004E0055005800E6E70BECBB8247007E2E7972D7AB750C
```
